# Generated by Django 5.2.5 on 2025-08-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'booking_hour')},
        ),
    ]
